# Generated by Django 4.2.2 on 2023-07-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='user',
        ),
    ]
