# Generated by Django 4.2.2 on 2023-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_firm_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
