# Generated by Django 4.2.2 on 2023-07-03 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_firm_owner_firm_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='shop_o',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='social_youtube',
        ),
        migrations.AddField(
            model_name='projects',
            name='shop_o',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone_number',
            field=models.CharField(blank=True, default='88000000000', max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть следующего формата: '+99999999'. До 15 символов.", regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
