# Generated by Django 4.2.2 on 2023-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_projects_shop_o'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='projects',
            name='shop_o',
            field=models.CharField(default='https://www.ozon.ru/seller/ip-valyan-a-n-675330/products/?miniapp=seller_675330', max_length=200),
        ),
    ]
