# Generated by Django 4.2.2 on 2023-07-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_projects_shop_o'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='owner',
        ),
    ]
